### ISSUE TITLE
A problem about tensor dimension

### ISSUE THREAD

**Issue by yuqing-liu-dut** [wchen342/SketchyGAN#3] opened 2018-05-09 11:46 UTC
Hi, all. When training the data, I've met a problem about tensor's dimensions. It says the dimensions of tensors are not matched. The info of error is shown in the picture.
![training error](https://user-images.githubusercontent.com/17153941/39813046-83f94386-53c1-11e8-8783-4d653fa03a1f.png)
 Could anyone help to solve this problem? Thank you .

By the way, my tensorflow's version is 1.7. I choose data of 4 labels for training, and the setting of csv file is shown in the attached picture. 
![csv setting](https://user-images.githubusercontent.com/17153941/39813064-95082124-53c1-11e8-91a1-de7f1aca4a7a.png)

Thanks.

**Comment by wchen342** [comment] 2018-05-11 00:00
The problem is caused by a recent change in Tensorflow. It should be fixed now.

**Closed as completed by wchen342** 2018-05-11 00:00 UTC
